namespace moe.yo3explorer.azusa.MediaLibrary.Control
{
    partial class GraphDataControl
    {
        /// <summary> 
        /// Erforderliche Designervariable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Verwendete Ressourcen bereinigen.
        /// </summary>
        /// <param name="disposing">True, wenn verwaltete Ressourcen gelöscht werden sollen; andernfalls False.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Vom Komponenten-Designer generierter Code

        /// <summary> 
        /// Erforderliche Methode für die Designerunterstützung. 
        /// Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl4 = new System.Windows.Forms.TabControl();
            this.graphdataTextTab = new System.Windows.Forms.TabPage();
            this.mediaGraphData = new System.Windows.Forms.TextBox();
            this.graphdataChartTab = new System.Windows.Forms.TabPage();
            this.graphDataPlot = new NPlot.Windows.PlotSurface2D();
            this.tabControl4.SuspendLayout();
            this.graphdataTextTab.SuspendLayout();
            this.graphdataChartTab.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl4
            // 
            this.tabControl4.Controls.Add(this.graphdataTextTab);
            this.tabControl4.Controls.Add(this.graphdataChartTab);
            this.tabControl4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl4.Location = new System.Drawing.Point(0, 0);
            this.tabControl4.Name = "tabControl4";
            this.tabControl4.SelectedIndex = 0;
            this.tabControl4.Size = new System.Drawing.Size(150, 150);
            this.tabControl4.TabIndex = 1;
            // 
            // graphdataTextTab
            // 
            this.graphdataTextTab.Controls.Add(this.mediaGraphData);
            this.graphdataTextTab.Location = new System.Drawing.Point(4, 22);
            this.graphdataTextTab.Name = "graphdataTextTab";
            this.graphdataTextTab.Padding = new System.Windows.Forms.Padding(3);
            this.graphdataTextTab.Size = new System.Drawing.Size(142, 124);
            this.graphdataTextTab.TabIndex = 0;
            this.graphdataTextTab.Text = "Texteingabe";
            this.graphdataTextTab.UseVisualStyleBackColor = true;
            // 
            // mediaGraphData
            // 
            this.mediaGraphData.AllowDrop = true;
            this.mediaGraphData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mediaGraphData.Enabled = false;
            this.mediaGraphData.Font = new System.Drawing.Font("Lucida Console", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mediaGraphData.Location = new System.Drawing.Point(3, 3);
            this.mediaGraphData.MaxLength = 999999999;
            this.mediaGraphData.Multiline = true;
            this.mediaGraphData.Name = "mediaGraphData";
            this.mediaGraphData.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.mediaGraphData.ShortcutsEnabled = false;
            this.mediaGraphData.Size = new System.Drawing.Size(136, 118);
            this.mediaGraphData.TabIndex = 1;
            this.mediaGraphData.WordWrap = false;
            // 
            // graphdataChartTab
            // 
            this.graphdataChartTab.Controls.Add(this.graphDataPlot);
            this.graphdataChartTab.Location = new System.Drawing.Point(4, 22);
            this.graphdataChartTab.Name = "graphdataChartTab";
            this.graphdataChartTab.Padding = new System.Windows.Forms.Padding(3);
            this.graphdataChartTab.Size = new System.Drawing.Size(142, 124);
            this.graphdataChartTab.TabIndex = 1;
            this.graphdataChartTab.Text = "Diagramm";
            this.graphdataChartTab.UseVisualStyleBackColor = true;
            // 
            // graphDataPlot
            // 
            this.graphDataPlot.AutoScaleAutoGeneratedAxes = false;
            this.graphDataPlot.AutoScaleTitle = false;
            this.graphDataPlot.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.graphDataPlot.DateTimeToolTip = false;
            this.graphDataPlot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.graphDataPlot.Legend = null;
            this.graphDataPlot.LegendZOrder = -1;
            this.graphDataPlot.Location = new System.Drawing.Point(3, 3);
            this.graphDataPlot.Name = "graphDataPlot";
            this.graphDataPlot.RightMenu = null;
            this.graphDataPlot.ShowCoordinates = true;
            this.graphDataPlot.Size = new System.Drawing.Size(136, 118);
            this.graphDataPlot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.graphDataPlot.TabIndex = 0;
            this.graphDataPlot.Text = "plotSurface2D1";
            this.graphDataPlot.Title = "";
            this.graphDataPlot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.graphDataPlot.XAxis1 = null;
            this.graphDataPlot.XAxis2 = null;
            this.graphDataPlot.YAxis1 = null;
            this.graphDataPlot.YAxis2 = null;
            // 
            // GraphDataControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.tabControl4);
            this.Name = "GraphDataControl";
            this.DragDrop += new System.Windows.Forms.DragEventHandler(this.GraphDataControl_DragDrop);
            this.DragEnter += new System.Windows.Forms.DragEventHandler(this.GraphDataControl_DragEnter);
            this.tabControl4.ResumeLayout(false);
            this.graphdataTextTab.ResumeLayout(false);
            this.graphdataTextTab.PerformLayout();
            this.graphdataChartTab.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl4;
        private System.Windows.Forms.TabPage graphdataTextTab;
        private System.Windows.Forms.TextBox mediaGraphData;
        private System.Windows.Forms.TabPage graphdataChartTab;
        private NPlot.Windows.PlotSurface2D graphDataPlot;
    }
}
